alias ls='ls --color=always'
alias grep='grep --color=always'
alias fgrep='fgrep --color=always'
alias egrep='egrep --color=always'
alias diff='diff --color=always'
alias ip='ip --color=always'
alias less='less -R'
alias vim='nvim'
alias icat='kitty +kitten icat'
