#!/usr/bin/env sh

# Set up the monitors
autorandr --change --default main

# Kill previous instances
pkill sxhkd
pkill conky
pkill picom
pkill polybar
pkill polkit-gnome-au

# Autostart
feh --bg-fill ~/Images/Wallpapers.jpg &
picom -b &
conky &
polybar main &
xrdb -merge ~/.Xresources &
setxkbmap -layout us,ru -option grp:caps_toggle &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xsetroot -cursor_name left_ptr &
sxhkd &

# Workspaces
bspc monitor -d 1 2 3 4 5

# Settings
bspc config border_width          5
bspc config window_gap            15
bspc config split_ratio           0.5
bspc config focus_follows_pointer false
bspc config normal_border_color   $COLOR_GREY_900
bspc config active_border_color   $COLOR_GREY_900
bspc config focused_border_color  $COLOR_BLUE
bspc config presel_feedback_color $COLOR_RED

# Window rules (xprop | grep WM_CLASS)
bspc rule -a kitty locked=on
bspc rule -a gnome-calculator state=floating sticky=on
