#!/usr/bin/env sh

# Kill previous instances
pkill sxhkd
pkill conky
pkill picom
pkill polybar
pkill polkit-gnome-au

# Autostart
sxhkd &
screen-offset &
sensensity &
feh --bg-fill ~/Images/Wallpapers.jpg &
picom -b &
conky &
/bin/polybar-init &
xrdb -merge ~/.Xresources &
setxkbmap -layout us,ru -option grp:caps_toggle &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Workspaces
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor DVI-D-0       -d 6 7 8 9 0

# Pointer actions
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side

# Settings
bspc config border_width          4
bspc config window_gap            15
bspc config normal_border_color   '#23252e'
bspc config active_border_color   '#23252e'
bspc config focused_border_color  '#0176ff'

bspc config presel_feedback_color '#fd2e59'
bspc config split_ratio           0.5
bspc config focus_follows_pointer false

bspc config single_monocle	     false
bspc config borderless_monocle   false
bspc config gapless_monocle      false 
bspc config paddingless_monocle	 false

# Window rules (xprop | grep WM_CLASS)
bspc rule -a discord monitor=DVI-D-0
bspc rule -a kitty locked=on
bspc rule -a gnome-calculator state=floating sticky=on
