#!/usr/bin/env sh

# Mouse sensensity
xinput set-prop 12 'libinput Accel Speed' -0.8
xinput set-prop 12 'libinput Accel Profile Enabled' 0, 1

# Monitors
xrandr --output HDMI-A-1 \
    --mode 1920x1080 \
    --rate 60.00 \
    --rotate normal \
    --pos 0x350
xrandr --output DisplayPort-0 \
    --primary \
    --mode 2560x1440 \
    --rate 165.00 \
    --rotate normal \
    --pos 1920x0

# Kill previous instances
pkill sxhkd
pkill conky
pkill picom
pkill polybar
pkill polkit-gnome-au
pkill flameshot

# Autostart
sxhkd &
feh --bg-fill ~/Images/Wallpapers.jpg &
picom -b &
conky &
polybar master &
polybar second &
xrdb -merge ~/.Xresources &
setxkbmap -layout us,ru -option grp:caps_toggle &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
flameshot &
xsetroot -cursor_name left_ptr &

# Workspaces
bspc monitor DisplayPort-0 -d 1 2 3 4 5
bspc monitor HDMI-A-1      -d 6 7 8 9

# Settings
bspc config border_width          5
bspc config window_gap            15
bspc config split_ratio           0.5
bspc config focus_follows_pointer false
bspc config normal_border_color   $COLOR_GREY_900
bspc config active_border_color   $COLOR_GREY_900
bspc config focused_border_color  $COLOR_BLUE
bspc config presel_feedback_color $COLOR_RED

# Window rules (xprop | grep WM_CLASS)
bspc rule -a kitty locked=on
bspc rule -a gnome-calculator state=floating sticky=on
bspc rule -a PacketTracer state=floating
