alias diff='diff --color=always'
alias egrep='egrep --color=always'
alias fgrep='fgrep --color=always'
alias grep='grep --color=always'
alias ip='ip --color=always'
alias less='less -R'
alias ls='ls --color=always'
alias chrome='google-chrome-stable'
alias icat='kitty +kitten icat'
alias bd='blobdrop'
alias vim='nvim'
alias y='yazi'
