if [ -d /etc/zsh/zshrc.d ]; then
    for zsh_file in /etc/zsh/zshrc.d/*; do
        source $zsh_file
    done
fi
if [ -d ~/.zshrc.d ]; then
    for zsh_file in ~/.zshrc.d/*; do
        source $zsh_file
    done
fi
