[system]
# The width of you monitor - 30 px for gaps
bar_width = 1890

# The path with the cpu temperature
# To get list, run:
#     for i in /sys/class/hwmon/*; do echo $(cat $i/name): $i/temp1_input; done
cpu_sensor = /sys/class/hwmon/hwmon4/temp1_input
cpu_base_temperature = 45
cpu_warn_temperature = 60

gpu_sensor = /sys/class/hwmon/hwmon5/temp1_input
gpu_base_temperature = 45
gpu_warn_temperature = 60

# Battery name
# To get lits, run:
#     ls /sys/class/power_supply/
battery_name = BATT
